home/urls.py
from django.urls import path
from .views import index,about,contact,teacher,tution,rent,rent_details,teacher_details,tution_details,take_rent


urlpatterns=[
    path("",index,name="index"),
    path("about",about,name="about"),
    path("contact",contact,name="contact"),
    path("teacher",teacher,name="teacher"),
    path("teacher_details/<int:id>",teacher_details,name="teacher_details"),
    path("tution",tution,name="tution"),
    path("tution_details/<int:id>",tution_details,name="tution_details"),
    path("rent",rent,name="rent"),
    path("rent_details/<int:id>",rent_details,name="rent_details"),
    path("take_rent/<int:owner_id>",take_rent,name="take_rent")
]

residential_area_service/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user_auth.urls")),
    path('', include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auth/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path("user_login",user_login,name="user_login"),
    path("forget_password",forget_password,name="forget_password"),
    path("user_signup",user_signup,name="user_signup"),
    path("user_dashboard",user_dashboard,name="user_dashboard"),
    path("user_logout",user_logout,name="user_logout"),
    path("house_rent_post",house_rent_post,name="house_rent_post"),
    path("teacher_post",teacher_post,name="teacher_post"),
    path("tution_post",tution_post,name="tution_post"),
    path("my_rent",my_rent,name="my_rent"),
    path("bill/<int:id>",bill,name="bill"),

]

user_auth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


# Create your models here.

# def current_user(request):
#     c_user=request.user
#     return c_user

class Poster(models.Model):
    poster_image_one=models.ImageField(upload_to="images/",verbose_name='poseter image one size-->width:1170 height:780')
    poster_image_two=models.ImageField(upload_to="images/")
    poster_image_three=models.ImageField(upload_to="images/")


class Rent(models.Model):
    title=models.CharField(max_length=1000)
    home_description=models.TextField()
    rent_price=models.IntegerField()
    total_square_feet=models.IntegerField()
    total_washroom=models.IntegerField()
    total_bed=models.IntegerField()
    phone_number=models.IntegerField()
    DHAKA = 'Dhaka'
    CHITTAGONG = 'Chittagong'
    DIVISION_CHOICES = (
        (DHAKA, 'Dhaka'),
        (CHITTAGONG, 'Chittagong')
    )

    division = models.CharField(choices=DIVISION_CHOICES, max_length=50)

    #Chittagong district
    GEC='Gec Moor'
    Chawkbazar='Chawkbazar'

    #Dhaka District
    Mirpur='mirpur'
    Gulshan='Gulshan'

    district_choices=(
        (GEC,'Gec Moor'),
        (Chawkbazar,'Chawkbazar'),
        (Mirpur,'Mirpur'),
        (Gulshan,'Gulshan'),
    )

    district=models.CharField(choices=district_choices,max_length=1000)

    home_image_one=models.ImageField(upload_to="images/")
    home_image_two=models.ImageField(upload_to="images/")
    home_image_three=models.ImageField(upload_to="images/")
    datetime=models.DateTimeField(default=now)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)


    def __str__(self):
        return f"{self.id} {self.title}"
    


class Teacher(models.Model):
    teacher_name=models.CharField(max_length=1000)
    email=models.EmailField()
    phone_number=models.IntegerField()
    DHAKA = 'Dhaka'
    CHITTAGONG = 'Chittagong'
    DIVISION_CHOICES = (
        (DHAKA, 'Dhaka'),
        (CHITTAGONG, 'Chittagong')
    )

    division = models.CharField(choices=DIVISION_CHOICES, max_length=50)

    #Chittagong district
    GEC='Gec Moor'
    Chawkbazar='Chawkbazar'

    #Dhaka District
    Mirpur='mirpur'
    Gulshan='Gulshan'

    district_choices=(
        (GEC,'Gec Moor'),
        (Chawkbazar,'Chawkbazar'),
        (Mirpur,'Mirpur'),
        (Gulshan,'Gulshan'),
    )

    district=models.CharField(choices=district_choices,max_length=1000)
    details_address=models.TextField()
    educations_details=models.TextField()
    teacher_image=models.ImageField(upload_to="images/")
    datetime=models.DateTimeField(default=now)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    rating=models.IntegerField(default=0)

    def __str__(self):
        return f"{self.id} {self.teacher_name}"



class Tution(models.Model):
    title=models.CharField(max_length=1000)
    email=models.EmailField()
    phone_number=models.IntegerField()
    DHAKA = 'Dhaka'
    CHITTAGONG = 'Chittagong'
    DIVISION_CHOICES = (
        (DHAKA, 'Dhaka'),
        (CHITTAGONG, 'Chittagong')
    )

    division = models.CharField(choices=DIVISION_CHOICES, max_length=50)

    #Chittagong district
    GEC='Gec Moor'
    Chawkbazar='Chawkbazar'

    #Dhaka District
    Mirpur='mirpur'
    Gulshan='Gulshan'

    district_choices=(
        (GEC,'Gec Moor'),
        (Chawkbazar,'Chawkbazar'),
        (Mirpur,'Mirpur'),
        (Gulshan,'Gulshan'),
    )

    district=models.CharField(choices=district_choices,max_length=1000)
    details_address=models.TextField()
    teacher_details=models.TextField()
    tution_image=models.ImageField(upload_to="images/")
    datetime=models.DateTimeField(default=now)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.id} {self.title}"



class Contact(models.Model):
    name=models.CharField(max_length=255)
    email=models.EmailField()
    phone=models.IntegerField()
    message=models.TextField()


    def __str__(self):
        return f"id:{self.id} name:{self.name}"
    

class RentComment(models.Model):
    rent=models.ForeignKey(Rent, on_delete=models.CASCADE)
    comment=models.TextField()
    username=models.CharField(max_length=100)
    datetime=models.DateTimeField(default=now)

    def __str__(self):
        return f"{self.username} {self.comment[0:20]}......"
    


class RentPayment(models.Model):
    name=models.CharField(max_length=200)
    country=models.CharField(max_length=200)
    division=models.CharField(max_length=200)
    district=models.CharField(max_length=200)
    address=models.CharField(max_length=200)
    zip_code=models.CharField(max_length=200)
    rent_price=models.CharField(max_length=200)
    payment=models.CharField(max_length=200)
    datetime=models.DateTimeField(default=now)

    def __str__(self):
        return f"{self.name}"

user_auth/forms.py
from django import forms
from .models import Rent,Teacher,Tution


class RentForm(forms.ModelForm):
    class Meta:
        model=Rent
        fields=('title','home_description','rent_price',
                'total_square_feet','total_washroom','total_bed','phone_number','division','district',
                'home_image_one','home_image_two', 'home_image_three','datetime','latitude','longitude')


class TeacherForm(forms.ModelForm):
    class Meta:
        model=Teacher
        fields=('teacher_name','email','phone_number','division','district',
                'details_address','educations_details','teacher_image','datetime')




class TutionForm(forms.ModelForm):
    class Meta:
        model=Tution
        fields=('title','email','phone_number','division','district',
                'details_address','teacher_details','datetime')

user_auth/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.forms import UserCreationForm,PasswordResetForm
from django.contrib import messages
from .forms import RentForm,TeacherForm,TutionForm
from home.models import RentPurchaserDetails

# Create your views here.

def user_login(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]

        user=authenticate(username=username,password=password)

        if user is not None:
            login(request,user)
            messages.success(request, "Welcome to user dashboard")
            return redirect("/user_dashboard")
            
        else:
            messages.error(request, "wrong username or password")
            return redirect(request.path)
        
    return render(request, "user_auth/login.html")



def forget_password(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to success page
            messages.error(request, "Password reset successfully")
            return redirect(user_login)
    else:
        form = PasswordResetForm()
    return render(request, 'user_auth/forget_password.html', {'form': form})



def user_logout(request):
    logout(request)
    return redirect("/")



def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, "Account Created successfully now login")
            return redirect(user_login)
    else:
        form = UserCreationForm()
    return render(request, 'user_auth/register.html', {'form': form})



def user_dashboard(request):
    if request.user.is_authenticated:
        user=User.objects.get(username=request.user)
        print(request.user)
        return render(request, "user_auth/user_dashboard.html")

    else:
        return redirect("/user_login")



def house_rent_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = RentForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.creator = request.user
                instance.save()
                
                messages.success(request,"Post Added Successfully")
                return redirect(user_dashboard)
            else:
                form = RentForm()
             
            return render(request, 'user_auth/house_rent_post.html', {
                'form': form
            })
        
        return render(request, 'user_auth/house_rent_post.html',{
            "c_username":request.user
        })

 

    else:
        return redirect("/user_login")
     


def teacher_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = TeacherForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.creator = request.user
                instance.save()
                
                messages.success(request,"Post Added Successfully")
                return redirect(user_dashboard)
            else:
                form = TeacherForm()
             
            return render(request, 'user_auth/teacher_post.html', {
                'form': form
            })
        
        return render(request, 'user_auth/teacher_post.html',{
            "c_username":request.user
        })


    else:
        return redirect("/user_login")
     



def tution_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = TutionForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.creator = request.user
                instance.save()
                
                messages.success(request,"Post Added Successfully")
                return redirect(user_dashboard)
            else:
                form = TutionForm()
             
            return render(request, 'user_auth/tution_post.html', {
                'form': form
            })
        
        
        


    else:
        return redirect("/user_login")
     


def my_rent(request):
    rent_details=RentPurchaserDetails.objects.filter(buyer_name=request.user).all()
    return render(request, 'user_auth/my_rent.html',{
        "rent_details":rent_details,
    })

def bill(request,id):
    post=RentPurchaserDetails.objects.filter(id=id).first()
    return render(request,"user_auth/bill.html",{
        "post":post,
    })

templates/user_auth/bill.html
{% extends "user_auth/base_user_dashboard.html" %}
{% load static %}
{% block content %}

             <!-- Begin Page Content -->
             <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Rent Bill </h1>
                <!-- <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p> -->

<form action="">

    <div class="container mt-5 my-10">
        
        <br>
            <!-- <h2>Owner Imformation</h2>
            <div class="form-group">
                <label for="fullname">Full Name</label>
                <input type="text" class="form-control" id="fullname" placeholder="Enter your full name">
            </div>
            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" placeholder="Enter your address">
            </div>
            <br><br><br> -->
            
            <h2>Billing address</h2>
            <br>

            <div class="form-group">
                <label for="fullname">Full Name</label>
                <input type="text" class="form-control" id="fullname" placeholder="Enter your full name">
            </div>
            <div class="form-group">
                <label for="country">Country</label>
                <input type="text" class="form-control" id="country" placeholder="Enter your country">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="city">Division</label>
                    <input type="text" class="form-control" id="city" placeholder="Enter your city">
                </div>
                <div class="form-group col-md-6">
                    <label for="state">District</label>
                    <input type="text" class="form-control" id="state" placeholder="Enter your state">
                </div>
            </div>

            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" placeholder="Enter your address">
            </div>

            <div class="form-group">
                <label for="zipcode">Zip Code</label>
                <input type="text" class="form-control" id="zipcode" placeholder="Enter your zip code">
            </div>

            <div class="form-group">
                <label for="country">Rent Price Monthly</label>
                <input type="text" class="form-control" value="{{ post.rent_price }} tk" disabled>
            </div>
            
        </form>
    </div>

    <div class="container mt-5">
        <h3>Payment Method</h3>
        <br>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img src="https://via.placeholder.com/200x200" class="card-img-top" alt="Image 1">
                    <div class="card-body">
                        <label>
                            <input type="radio" name="payment_method" value="image1.jpg">
                            Bikash
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="https://via.placeholder.com/200x200" class="card-img-top" alt="Image 2">
                    <div class="card-body">
                        <label>
                            <input type="radio" name="payment_method" value="image2.jpg">
                          nogod
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="https://via.placeholder.com/200x200" class="card-img-top" alt="Image 3">
                    <div class="card-body">
                        <label>
                            <input type="radio" name="payment_method" value="image3.jpg">
                            Rocket
                        </label>
                    </div>
                </div>
            </div>
        </div>

        

    </form>
 <br><br><br>
{% endblock %}

templates/user_auth/forget_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    
                                    {% block content %}
                                        <h2>Forget Password</h2>
                                        <form method="post">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                            <button type="submit">Submit</button>
                                        </form>
                                    {% endblock %}

                                    
                                    <!-- <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

templates/user_auth/house_rent_post.html
{% extends "user_auth/base_user_dashboard.html" %}
{% load static %}
{% block content %}
{% block head %}
<style>
    label{
        display: block;
        font-weight: bolder;
        font-size: 25px;
        color: lightcoral;
        
    }
    input{
        display: block;
        width: 40vw;
        margin: 10px;
        height: 50px;
        font-weight: bolder;
        color: black;
        
    }

    textarea{
        width: 40vw;
    }

    select{
        display: block;
        width: 40vw;
        margin: 10px;
        height: 50px;

    }
</style>
{% endblock %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Add House Rent Post</h1>
    <p class="mb-4">If you have any house for rent you can give rent post.</p>
    

    <div class="container">
        <form method="post" action="{% url 'house_rent_post' %}" id="rent" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            
            <button class="btn btn-lg btn-primary" type="submit" form="rent">Upload</button>
        </form>
    </div>



</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        var divisionField = $('#id_division');
        var districtField = $('#id_district');
        var districtOptions = districtField.html();

        divisionField.change(function () {
            var selectedCity = divisionField.val();
            var newOptions = districtOptions;

            if (selectedCity == 'Dhaka') {
                newOptions = '<option value="Mirpur">Mirpur</option><option value="Gulshan">Gulshan</option>';
            } else if (selectedCity == 'Chittagong') {
                newOptions = '<option value=Gec Moor">Gec Moor</option><option value="Chawkbazar">Chawkbazar</option>';
            }

            districtField.html(newOptions);
        });
    });
</script>

{% endblock %}

templates/user_auth/my_rent.html
{% extends "user_auth/base_user_dashboard.html" %}
{% load static %}
{% block content %}

             <!-- Begin Page Content -->
             <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">My Rent </h1>
                <!-- <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p> -->

                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Owner username</th>
                                        <th>District</th>
                                        <th>Division</th>
                                        <th>Rent Price</th>
                                        <th> total square foot</th>
                                        <th>washroom</th>
                                        <th>Bedroom</th>
                                        <th>Pay rent</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Owner username</th>
                                        <th>District</th>
                                        <th>Division</th>
                                        <th>Rent Price</th>
                                        <th> total square foot</th>
                                        <th>washroom</th>
                                        <th>Bedroom</th>
                                        <th>Pay rent</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    {% for d in rent_details %}
                                    <tr>
                                        <td>{{ d.owner_name }}</td>
                                        <td>{{ d.district }}</td>
                                        <td>{{ d.division }}</td>
                                        <td>{{ d.rent_price }}</td>
                                        <td>{{ d.square_foot }}</td>
                                        <td>{{ d.washroom }}</td>
                                        <td>{{ d.bedroom }}</td>
                                        <td><a href="{% url "bill" d.id %}"><button class="btn btn-info">Pay</button></a></td>
                                    </tr>

                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

{% endblock %}

templates/user_auth/teacher_post.html
{% extends "user_auth/base_user_dashboard.html" %}
{% load static %}
{% block content %}
{% block head %}
<style>
    label{
        display: block;
        font-weight: bolder;
        font-size: 25px;
        color: lightcoral;
        
    }
    input{
        display: block;
        width: 40vw;
        margin: 10px;
        height: 50px;
        font-weight: bolder;
        color: black;
        
    }

    textarea{
        width: 40vw;
    }

    select{
        display: block;
        width: 40vw;
        margin: 10px;
        height: 50px;

    }
</style>
{% endblock %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Add Teacher Post</h1>
    <!-- <p class="mb-4">If you have any house for rent you can give rent post.</p> -->
    

    <div class="container">
        <form method="post" action="{% url 'teacher_post' %}" id="teacher" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            
            <button class="btn btn-lg btn-primary" type="submit" form="teacher">Upload</button>
        </form>
    </div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        var divisionField = $('#id_division');
        var districtField = $('#id_district');
        var districtOptions = districtField.html();

        divisionField.change(function () {
            var selectedCity = divisionField.val();
            var newOptions = districtOptions;

            if (selectedCity == 'Dhaka') {
                newOptions = '<option value="Mirpur">Mirpur</option><option value="Gulshan">Gulshan</option>';
            } else if (selectedCity == 'Chittagong') {
                newOptions = '<option value=Gec Moor">Gec Moor</option><option value="Chawkbazar">Chawkbazar</option>';
            }

            districtField.html(newOptions);
        });
    });
</script>

{% endblock %}

templates/user_auth/tution_post.html
{% extends "user_auth/base_user_dashboard.html" %}
{% load static %}
{% block content %}
{% block head %}
<style>
    label{
        display: block;
        font-weight: bolder;
        font-size: 25px;
        color: lightcoral;
        
    }
    input{
        display: block;
        width: 40vw;
        margin: 10px;
        height: 50px;
        font-weight: bolder;
        color: black;
        
    }

    textarea{
        width: 40vw;
    }

    select{
        display: block;
        width: 40vw;
        margin: 10px;
        height: 50px;

    }
</style>
{% endblock %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Add Tution Post</h1>
    <!-- <p class="mb-4">If you have any house for rent you can give rent post.</p> -->
    

    <div class="container">
        <form method="post" action="{% url 'tution_post' %}" id="tution" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            
            <button class="btn btn-lg btn-primary" type="submit" form="tution">Upload</button>
        </form>
    </div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        var divisionField = $('#id_division');
        var districtField = $('#id_district');
        var districtOptions = districtField.html();

        divisionField.change(function () {
            var selectedCity = divisionField.val();
            var newOptions = districtOptions;

            if (selectedCity == 'Dhaka') {
                newOptions = '<option value="Mirpur">Mirpur</option><option value="Gulshan">Gulshan</option>';
            } else if (selectedCity == 'Chittagong') {
                newOptions = '<option value=Gec Moor">Gec Moor</option><option value="Chawkbazar">Chawkbazar</option>';
            }

            districtField.html(newOptions);
        });
    });
</script>

{% endblock %}